## variables in terraform 

# variable "Ec2 Instance Type"

variable "ec2-type" {
  description = "Ec2 Instance Type"
  type=string
  default = "t2.micro"
}

# variable "Key-pair generated by Terraform"

variable "generated_key_name" {
  type        = string
  default     = "terraform-key-pair"
  description = "Key-pair generated by Terraform"
}

# variable "local variable"

locals {
  tags= {
    env="dev"
    project = "aws-vpc"
  }
}
